name: tourism_app
description: A new Flutter project for tourism places in Sulaymaniyah.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.4+3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2  # Add this dependency for API requests
  dio: ^5.3.2
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  
  
flutter:
  uses-material-design: true
  assets:
    - assets/azmar.jpg
    - assets/millennium.jpg
    - assets/chaviland.jpg
    - assets/wallpaper.jpg
    - assets/museum.jpg
    - assets/amna_suraka.jpg

    # You can add more assets here